const prefixDict = {
  doz: "的",
  mar: "願",
  bin: "協",
  wan: "砂",
  sam: "妥",
  lit: "摧",
  sig: "疵",
  hid: "丫",
  fid: "虱",
  lis: "僮",
  sog: "是",
  dir: "李",
  wac: "輪",
  sab: "恭",
  wis: "謠",
  sib: "栗",
  rig: "憧",
  sol: "鸚",
  dop: "坷",
  mod: "玆",
  fog: "不",
  lid: "底",
  hop: "略",
  dar: "塔",
  dor: "缸",
  lor: "菊",
  hod: "懺",
  fol: "蒹",
  rin: "笆",
  tog: "衲",
  sil: "我",
  mir: "約",
  hol: "慧",
  pas: "賀",
  lac: "芒",
  rov: "瘦",
  liv: "琨",
  dal: "憩",
  sat: "竽",
  lib: "杳",
  tab: "一",
  han: "雄",
  tic: "幻",
  pid: "魂",
  tor: "陵",
  bol: "鈞",
  fos: "闕",
  dot: "懊",
  los: "梖",
  dil: "姒",
  for: "有",
  pil: "課",
  ram: "臉",
  tir: "睛",
  win: "雯",
  tad: "匿",
  bic: "萱",
  dif: "聾",
  roc: "賏",
  wid: "嬿",
  bis: "大",
  das: "答",
  mid: "短",
  lop: "逸",
  ril: "軌",
  nar: "磚",
  dap: "悵",
  mol: "盎",
  san: "閨",
  loc: "忪",
  nov: "在",
  sit: "令",
  nid: "鷹",
  tip: "旗",
  sic: "蝦",
  rop: "噓",
  wit: "輒",
  nat: "婊",
  pan: "浙",
  min: "鯤",
  rit: "人",
  pod: "深",
  mot: "衝",
  tam: "薩",
  tol: "寸",
  sav: "縛",
  pos: "搏",
  nap: "盔",
  nop: "疙",
  som: "槁",
  fin: "瞭",
  fon: "票",
  ban: "朝",
  mor: "丸",
  wor: "呦",
  sip: "嘟",
  ron: "榕",
  nor: "巒",
  bot: "蓁",
  wic: "饞",
  soc: "中",
  wat: "達",
  dol: "忍",
  mag: "厚",
  pic: "灑",
  dav: "盆",
  bid: "飢",
  bal: "矜",
  tim: "烷",
  tas: "甡",
  mal: "到",
  lig: "演",
  siv: "遊",
  tag: "齋",
  pad: "貞",
  sal: "債",
  div: "搗",
  dac: "凜",
  tan: "喈",
  sid: "癩",
  fab: "資",
  tar: "早",
  mon: "河",
  ran: "芬",
  nis: "蜂",
  wol: "霞",
  mis: "渣",
  pal: "鋪",
  las: "跩",
  dis: "咋",
  map: "要",
  rab: "賣",
  tob: "批",
  rol: "革",
  lat: "鑽",
  lon: "挽",
  nod: "眺",
  nav: "鵡",
  fig: "酣",
  nom: "翌",
  nib: "可",
  pag: "棒",
  sop: "混",
  ral: "庸",
  bil: "廁",
  had: "逍",
  doc: "虞",
  rid: "蜴",
  moc: "卍",
  pac: "栱",
  rav: "以",
  rip: "夠",
  fal: "窗",
  tod: "舒",
  til: "鶴",
  tin: "畔",
  hap: "俯",
  mic: "惚",
  fan: "遏",
  pat: "嘮",
  tac: "這",
  lab: "黑",
  mog: "鄉",
  sim: "飲",
  son: "摔",
  pin: "蘊",
  lom: "紳",
  ric: "疇",
  tap: "亙",
  fir: "軼",
  has: "個",
  bos: "院",
  bat: "蛋",
  poc: "閉",
  hac: "盒",
  tid: "頸",
  hav: "謗",
  sap: "羈",
  lin: "贔",
  dib: "馱",
  hos: "你",
  dab: "假",
  bit: "季",
  bar: "勵",
  rac: "蟲",
  par: "獲",
  lod: "瓏",
  dos: "媛",
  bor: "萬",
  toc: "鉻",
  hil: "會",
  mac: "麯",
  tom: "散",
  dig: "頓",
  fil: "氛",
  fas: "畏",
  mit: "咫",
  hob: "塹",
  har: "掐",
  mig: "駑",
  hin: "好",
  rad: "火",
  mas: "冊",
  hal: "仰",
  rag: "悄",
  lag: "喂",
  fad: "俏",
  top: "泛",
  mop: "蛹",
  hab: "阜",
  nil: "為",
  nos: "準",
  mil: "棄",
  fop: "閣",
  fam: "霖",
  dat: "脾",
  nol: "淆",
  din: "瘡",
  hat: "驥",
  nac: "啐",
  ris: "上",
  fot: "百",
  rib: "熟",
  hoc: "孟",
  nim: "愧",
  lar: "姬",
  fit: "蜀",
  wal: "韶",
  rap: "樊",
  sar: "猷",
  nal: "來",
  mos: "談",
  lan: "奬",
  don: "昌",
  dan: "斜",
  lad: "赴",
  dov: "楠",
  riv: "憋",
  bac: "雱",
  pol: "癈",
  lap: "就",
  tal: "勝",
  pit: "唯",
  nam: "訪",
  bon: "屍",
  ros: "囊",
  ton: "乞",
  fod: "祁",
  pon: "戾",
  sov: "蝨",
  noc: "學",
  sor: "碟",
  lav: "藏",
  mat: "緒",
  mip: "循",
  fip: "噪",
};

const suffixDict = {
  zod: "詛",
  nec: "詬",
  bud: "彆",
  wes: "淂",
  sev: "交",
  per: "術",
  sut: "婚",
  let: "裕",
  ful: "倆",
  pen: "熄",
  syt: "勻",
  dur: "搔",
  wep: "匱",
  ser: "楹",
  wyl: "也",
  sun: "推",
  ryp: "鏡",
  syx: "勿",
  dyr: "堡",
  nup: "锡",
  heb: "貂",
  peg: "蜥",
  lup: "崛",
  dep: "氨",
  dys: "用",
  put: "存",
  lug: "緊",
  hec: "州",
  ryt: "旺",
  tyv: "訣",
  syd: "寰",
  nex: "袒",
  lun: "谘",
  mep: "菅",
  lut: "能",
  sep: "治",
  pes: "猜",
  del: "闡",
  sul: "惡",
  ped: "肇",
  tem: "迋",
  led: "奄",
  tul: "湃",
  met: "濘",
  wen: "如",
  byn: "離",
  hex: "喝",
  feb: "搶",
  pyl: "叉",
  dul: "璋",
  het: "敞",
  mev: "忱",
  rut: "賬",
  tyl: "戟",
  wyd: "文",
  tep: "易",
  bes: "尊",
  dex: "掃",
  sef: "燕",
  wyc: "暈",
  bur: "跪",
  der: "玖",
  nep: "粟",
  pur: "拮",
  rys: "時",
  reb: "往",
  den: "乾",
  nut: "糊",
  sub: "津",
  pet: "濁",
  rul: "囚",
  syn: "拌",
  reg: "譙",
  tyd: "踞",
  sup: "沒",
  sem: "況",
  wyn: "縣",
  rec: "宙",
  meg: "臣",
  net: "伐",
  sec: "溺",
  mul: "悴",
  nym: "驂",
  tev: "忐",
  web: "說",
  sum: "晚",
  mut: "伯",
  nyx: "嘗",
  rex: "喪",
  teb: "峽",
  fus: "駱",
  hep: "祠",
  ben: "焜",
  mus: "驊",
  wyx: "他",
  sym: "示",
  sel: "偏",
  ruc: "菩",
  dec: "茂",
  wex: "竊",
  syr: "憬",
  wet: "扼",
  dyl: "濺",
  myn: "彧",
  mes: "看",
  det: "證",
  bet: "偷",
  bel: "賜",
  tux: "椅",
  tug: "枕",
  myr: "葦",
  pel: "髏",
  syp: "漳",
  ter: "紕",
  meb: "提",
  set: "段",
  dut: "鞦",
  deg: "赤",
  tex: "纏",
  sur: "倘",
  fel: "脊",
  tud: "築",
  nux: "欸",
  rux: "罈",
  ren: "那",
  wyt: "導",
  nub: "層",
  med: "喊",
  lyt: "刑",
  dus: "慌",
  neb: "瑤",
  rum: "蛤",
  tyn: "葆",
  seg: "郢",
  lyx: "問",
  pun: "傷",
  res: "顆",
  red: "盜",
  fun: "脈",
  rev: "垮",
  ref: "疆",
  mec: "茱",
  ted: "瘩",
  rus: "聒",
  bex: "生",
  leb: "調",
  dux: "食",
  ryn: "擎",
  num: "杉",
  pyx: "帕",
  ryg: "乍",
  ryx: "騏",
  fep: "剷",
  tyr: "跚",
  tus: "過",
  tyc: "團",
  leg: "淡",
  nem: "勸",
  fer: "泊",
  mer: "瑩",
  ten: "杆",
  lus: "捶",
  nus: "恙",
  syl: "犛",
  tec: "下",
  mex: "七",
  pub: "申",
  rym: "奮",
  tuc: "撒",
  fyl: "琦",
  lep: "眸",
  deb: "須",
  ber: "陞",
  mug: "駟",
  hut: "請",
  tun: "永",
  byl: "冠",
  sud: "慈",
  pem: "遞",
  dev: "廂",
  lur: "竄",
  def: "亢",
  bus: "榻",
  bep: "姣",
  run: "天",
  mel: "剛",
  pex: "衣",
  dyt: "盡",
  byt: "疲",
  typ: "渺",
  lev: "孽",
  myl: "葔",
  wed: "潞",
  duc: "謫",
  fur: "們",
  fex: "哥",
  nul: "僅",
  luc: "汙",
  len: "杆",
  ner: "髒",
  lex: "卅",
  rup: "艸",
  ned: "哞",
  lec: "堐",
  ryd: "所",
  lyd: "甚",
  fen: "帳",
  wel: "狐",
  nyd: "趁",
  hus: "削",
  rel: "夭",
  rud: "篩",
  nes: "錘",
  hes: "忑",
  fet: "多",
  des: "德",
  ret: "贊",
  dun: "罰",
  ler: "欠",
  nyr: "鑼",
  seb: "簧",
  hul: "嶽",
  ryl: "琢",
  lud: "焊",
  rem: "麽",
  lys: "殺",
  fyn: "購",
  wer: "幽",
  ryc: "盈",
  sug: "虐",
  nys: "徘",
  nyl: "嶽",
  lyn: "簷",
  dyn: "餉",
  dem: "小",
  lux: "怕",
  fed: "犯",
  sed: "準",
  bec: "晃",
  mun: "豔",
  lyr: "饅",
  tes: "慵",
  mud: "僕",
  nyt: "鈉",
  byr: "想",
  sen: "包",
  weg: "敬",
  fyr: "兼",
  mur: "蛇",
  tel: "薇",
  rep: "趴",
  teg: "戮",
  pec: "厘",
  nel: "婁",
  nev: "得",
  fes: "列",
};

const patPInput = document.querySelector("#patPInput");
const sealArea1 = document.querySelector("#sealArea1");
const sealArea2 = document.querySelector("#sealArea2");
const sealArea3 = document.querySelector("#sealArea3");
const sealArea4 = document.querySelector("#sealArea4");
const validP = document.querySelector("#validP");

const sealMaker = (x) => {
  if (x.length % 3 === 0) {
    if (x.length === 3) {
      if (!(x in suffixDict)) {
        return "invalid @p";
      } else {
        return suffixDict[x];
      }
    } else if (x.length === 6) {
      let first = prefixDict[x.substring(0, 3)];
      let second = suffixDict[x.substring(3)];
      let str = first + second;

      if (
        typeof str === "number" ||
        typeof first === "undefined" ||
        typeof second === "undefined"
      ) {
        return "invalid @p";
      } else {
        return str;
      }
    } else if (x.length === 9) {
      return "invalid @p";
    } else if (x.length === 12) {
      let first = prefixDict[x.substring(0, 3)];
      let second = suffixDict[x.substring(3, 6)];
      let third = prefixDict[x.substring(6, 9)];
      let fourth = suffixDict[x.substring(9)];

      if (
        typeof first != "undefined" &&
        typeof second != "undefined" &&
        typeof third != "undefined" &&
        typeof fourth != "undefined"
      ) {
        return first + second + third + fourth;
      } else {
        return "invalid @p";
      }
    }
  }
  return "invalid @p";
};

const visual = (patp) => {
  if (patp === "invalid @p") {
    validP.innerHTML = "invalid @p";
    sealArea1.innerHTML = "";
    sealArea2.innerHTML = "";
    sealArea3.innerHTML = "";
    sealArea4.innerHTML = "";
  } else {
    validP.innerHTML = "";
    if (patp.length === 1) {
      sealArea1.innerHTML = patp.substring(0);
      sealArea2.innerHTML = "";
      sealArea3.innerHTML = "";
      sealArea4.innerHTML = "";
    } else if (patp.length === 2) {
      sealArea1.innerHTML = patp.substring(0, 1);
      sealArea2.innerHTML = patp.substring(1, 2);
      sealArea3.innerHTML = "";
      sealArea4.innerHTML = "";
    } else if (patp.length === 4) {
      sealArea1.innerHTML = patp.substring(0, 1);
      sealArea2.innerHTML = patp.substring(1, 2);
      sealArea3.innerHTML = patp.substring(2, 3);
      sealArea4.innerHTML = patp.substring(3, 4);
    }
  }
};

patPInput.addEventListener("input", (e) => {
  x = e.target.value;
  visual(sealMaker(x));
});
